### ISSUE TITLE
Crashes after several restart - Failed to get ping responses from 1 of 1 active silos

### ISSUE THREAD

**Issue by wangjia184** [OrleansContrib/Orleans.Clustering.Kubernetes#52]
Running Orleans in K8S StatefulSet, I try to delete the POD forcely and then POD restart, it crashes.

```
System.AggregateException: One or more errors occurred. (Failed to get ping responses from 1 of 1 active silos. Newly joining silos validate connectivity with all active silos that have recently updated their 'I Am Alive' value before joining the cluster. Successfully contacted: []. Failed to get response from: [S10.18.123.218:11111:361110184])
 ---> Orleans.Runtime.MembershipService.OrleansClusterConnectivityCheckFailedException: Failed to get ping responses from 1 of 1 active silos. Newly joining silos validate connectivity with all active silos that have recently updated their 'I Am Alive' value before joining the cluster. Successfully contacted: []. Failed to get response from: [S10.18.123.218:11111:361110184]
   at Orleans.Runtime.MembershipService.MembershipAgent.ValidateInitialConnectivity()
   at Orleans.Runtime.MembershipService.MembershipAgent.BecomeActive()
   at Orleans.Runtime.MembershipService.MembershipAgent.<>c__DisplayClass26_0.<<Orleans-ILifecycleParticipant<Orleans-Runtime-ISiloLifecycle>-Participate>g__OnBecomeActiveStart|6>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct)
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute()
   at Orleans.Runtime.Silo.StartAsync(CancellationToken cancellationToken)
   at Orleans.Hosting.SiloHost.StartAsync(CancellationToken cancellationToken)
   at Orleans.Hosting.SiloHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at UBS.OrleansServer.EntryPoint.Start() in /app/UBS/OrleansServer/EntryPoint.cs:line 102
   --- End of inner exception stack trace ---
```

Please what could be the reason?
More details can be found here: https://stackoverflow.com/questions/67944854/microsoft-orleans-k8s-crashes/67945115#67945115

**Comment by wangjia184** [comment]
Tried to set `replica` to 3,  all PODs crashed on startup.  Even I cleaned consul key/values

**Comment by xontab** [comment]
Are you using K8s membership via `UseKubeMembership()` extension method.  Looks like in the examples above you are only using official Orleans libraries such as `Microsoft.Orleans.OrleansConsulUtils` and `Microsoft.Orleans.Hosting.Kubernetes`.  If so you need to report this issue to the official Orleans project i.e. https://github.com/dotnet/orleans
